### ISSUE TITLE
Add related awesome lists

### ISSUE THREAD

**Issue by noteflakes** [ciconia/awesome-music#10]
Existing lists:
- https://github.com/adius/awesome-music-production

And also create a separate awesome-lilypond list.

**Comment by noteflakes** [comment]
Awesome sheet music: https://github.com/adius/awesome-sheet-music

**Comment by ybayle** [comment]
Hi and thanks for this great list. Here is a new suggestion: https://github.com/ybayle/awesome-music-listening
