### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [ciconia/awesome-music#71]
Hi there, 1st of all thanks for this cool list !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under  the [AUDIO section](https://github.com/FORARTfe/HyMPS#-) \ [Collections page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Collections.md#-)), can you please add a GH-compliant license file for it ?

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge:

![](https://badgen.net/github/license/noteflakes/awesome-music)
(badge-generator URL: https://badgen.net/github/license/noteflakes/awesome-music)

If needed, we suggest you to check @BillyDM's [Awesome Audio DSP](https://github.com/BillyDM/awesome-audio-dsp) to get an example of how to "rightly" set the [Public Domain license in GH](https://github.com/BillyDM/awesome-audio-dsp/blob/main/LICENSE).
And, of course, the relative badge:
![](https://badgen.net/github/license/BillyDM/awesome-audio-dsp)
(badge-generator URL: https://badgen.net/github/license/BillyDM/awesome-audio-dsp)

Last but not least, even if it's not an "awesome" collection, please add our project - using the official link: https://www.forart.it/HyMPS - to your list too.

Thanks in advance !

**Comment by noteflakes** [comment]
Hi and apologies for the late reply.

- As stated in the README, this repository is in the public domain. If you wish to add a license file, feel free to submit a PR.
- If you wish to add a site to this list, please follow the contribution guidelines in the README and submit a PR.
